version: '3.8'

services:
  # --- INFRASTRUCTURE ---
  postgres:
    image: postgres:15
    container_name: job_platform_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: job_platform
    ports:
      - "5432:5432"
    networks:
      - job-platform-net

  redis:
    image: redis:alpine
    container_name: job_platform_redis
    ports:
      - "6379:6379"
    networks:
      - job-platform-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - job-platform-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
      - job-platform-net

  # --- MICROSERVICES ---
  api-gateway:
    build: ./backend/api-gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    environment:
      - USER_SERVICE_URL=http://user-service:8001
      - RESUME_SERVICE_URL=http://resume-service:8002
      - JOB_SERVICE_URL=http://job_service:8003
      - SALARY_SERVICE_URL=http://salary-service:8005
      - INTERVIEW_SERVICE_URL=http://interview-service:8006
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - kafka
      - redis
    networks:
      - job-platform-net

  user-service:
    build: ./backend/user-service
    container_name: user_service
    ports:
      - "8001:8001"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/job_platform
      - SECRET_KEY=your-secret-key-here
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    depends_on:
      - postgres
      - kafka
      - redis
    networks:
      - job-platform-net

  resume-service:
    build: ./backend/resume-service
    container_name: resume_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/job_platform
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002
    depends_on:
      - postgres
      - kafka
    networks:
      - job-platform-net

  job-service:
    build: ./backend/job-service
    container_name: job-service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/job_platform
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    command: uvicorn app.main:app --host 0.0.0.0 --port 8003
    depends_on:
      - postgres
      - kafka
    networks:
      - job-platform-net

  salary-service:
    build: ./backend/salary-service
    container_name: salary_service
    ports:
      - "8005:8005"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_URL=redis://redis:6379
    command: uvicorn app.main:app --host 0.0.0.0 --port 8005
    depends_on:
      - kafka
      - redis
    networks:
      - job-platform-net

  interview-service:
    build: ./backend/interview-service
    container_name: interview_service
    ports:
      - "8006:8006"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    command: uvicorn app.main:app --host 0.0.0.0 --port 8006
    depends_on:
      - kafka
    networks:
      - job-platform-net

networks:
  job-platform-net:
    driver: bridge